"""System Guide & Playbook — in-app view of docs/System_Guide.md, plus a PDF
download of the same content (generated by docs/generate_guide_pdf.py into
assets/Dashboard_Pro_System_Guide.pdf).

Re-run ``python docs/generate_guide_pdf.py`` after editing the guide so the
downloadable PDF stays in sync with what this page renders live.
"""
from __future__ import annotations

import os

import streamlit as st

from src.pages_lib.base import BloombergPage, PageContext

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_GUIDE_MD = os.path.join(_REPO_ROOT, "docs", "System_Guide.md")
_GUIDE_PDF = os.path.join(_REPO_ROOT, "assets", "Dashboard_Pro_System_Guide.pdf")


class SystemGuidePage(BloombergPage):
    """Orientation page: the full trading-system guide, readable in-app or
    downloadable as a PDF for offline reading/sharing."""

    def configure(self) -> PageContext:
        return PageContext(code="GUID", title="System Guide", icon="📖")

    def sidebar(self, ctx: PageContext) -> None:
        st.markdown(
            '<div style="color:#00ff41;font-weight:700;letter-spacing:0.15em;'
            'text-transform:uppercase;font-size:11px;">GUIDE</div>',
            unsafe_allow_html=True,
        )
        st.caption(
            "Every page, what its numbers mean, and how to turn them into "
            "one disciplined trade decision — plus the new Instrument "
            "Predictor's full methodology."
        )
        if os.path.exists(_GUIDE_PDF):
            with open(_GUIDE_PDF, "rb") as fh:
                st.download_button(
                    "📥 Download PDF", data=fh.read(),
                    file_name="Dashboard_Pro_System_Guide.pdf",
                    mime="application/pdf", width="stretch",
                )
        else:
            st.caption("PDF not yet generated — run "
                      "`python docs/generate_guide_pdf.py`.")

    def body(self, ctx: PageContext) -> None:
        if not os.path.exists(_GUIDE_MD):
            st.error(f"Guide source not found at {_GUIDE_MD}.")
            return
        with open(_GUIDE_MD, "r", encoding="utf-8") as fh:
            st.markdown(fh.read())
