"""
event_week_vol_tab.py
=====================
Empirical test: is there a "busy week of the month" pattern in FX volatility,
and does anchoring to events (NFP / CPI / FOMC / BoJ / SARB) explain it
better than the raw week number?

Uses yfinance daily OHLC.

Two competing groupings are computed for every instrument:
  1. NAIVE:  week-of-month (1..5) -> mean daily ATR%
  2. EVENT-ANCHORED: days-to-nearest-event (-5..+5) -> mean daily ATR%

If the event-anchored profile shows a sharper, cleaner peak than the
week-of-month profile, the "busy week" is an artifact of the event calendar,
not the calendar week itself. That is the hypothesis being tested.

Entry point: render_event_week_vol_tab()
Standalone:  streamlit run pages/event_week_vol_tab.py (also auto-registers as
a multipage page — see src/pages_lib/navigation.py)
"""

from __future__ import annotations

import calendar
import datetime as dt

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import yfinance as yf

from src.instruments import INSTRUMENTS as _REGISTRY_INSTRUMENTS
from src.services.alert_service import NotifyCache
from src.services.tool_log import log_tool_usage

# ---------------------------------------------------------------------------
# Instruments — sourced from the shared registry (src/instruments/registry.py)
# so this page covers the same universe as every other page.
# ---------------------------------------------------------------------------
INSTRUMENTS: dict[str, str] = {
    name: info.ticker for name, info in _REGISTRY_INSTRUMENTS.items()
}

# ---------------------------------------------------------------------------
# Event calendars.
# NFP is generated by rule (first Friday of the month).
# FOMC dates below are the *decision* days and are reliable through 2026.
# BoJ / SARB / CPI dates are best-effort seeds — VERIFY AND EXTEND these
# (or load your own via the CSV uploader in the UI; format: date,event).
# ---------------------------------------------------------------------------
FOMC_DATES = [
    # 2023
    "2023-02-01", "2023-03-22", "2023-05-03", "2023-06-14",
    "2023-07-26", "2023-09-20", "2023-11-01", "2023-12-13",
    # 2024
    "2024-01-31", "2024-03-20", "2024-05-01", "2024-06-12",
    "2024-07-31", "2024-09-18", "2024-11-07", "2024-12-18",
    # 2025
    "2025-01-29", "2025-03-19", "2025-05-07", "2025-06-18",
    "2025-07-30", "2025-09-17", "2025-10-29", "2025-12-10",
    # 2026 (scheduled)
    "2026-01-28", "2026-03-18", "2026-04-29", "2026-06-17",
    "2026-07-29", "2026-09-16", "2026-10-28", "2026-12-09",
]

# BoJ policy decision days (announcement = second day of meeting).
# Seed list — verify against boj.or.jp and extend.
BOJ_DATES = [
    "2024-01-23", "2024-03-19", "2024-04-26", "2024-06-14",
    "2024-07-31", "2024-09-20", "2024-10-31", "2024-12-19",
    "2025-01-24", "2025-03-19", "2025-05-01", "2025-06-17",
    "2025-07-31", "2025-09-19", "2025-10-30", "2025-12-19",
]

# SARB MPC decision Thursdays (6 per year: Jan/Mar/May/Jul/Sep/Nov).
# Seed list — verify against resbank.co.za and extend.
SARB_DATES = [
    "2024-01-25", "2024-03-27", "2024-05-30", "2024-07-18",
    "2024-09-19", "2024-11-21",
    "2025-01-30", "2025-03-20", "2025-05-29", "2025-07-31",
    "2025-09-18", "2025-11-20",
]

# US CPI release days — not rule-computable, seed with recent known dates
# and extend via CSV upload. (BLS publishes the schedule a year ahead.)
US_CPI_DATES = [
    "2024-01-11", "2024-02-13", "2024-03-12", "2024-04-10",
    "2024-05-15", "2024-06-12", "2024-07-11", "2024-08-14",
    "2024-09-11", "2024-10-10", "2024-11-13", "2024-12-11",
    "2025-01-15", "2025-02-12", "2025-03-12", "2025-04-10",
    "2025-05-13", "2025-06-11", "2025-07-15", "2025-08-12",
    "2025-09-11", "2025-10-15", "2025-11-13", "2025-12-10",
]

# Which event calendars matter for which instrument. Any JPY leg pulls in BOJ,
# any ZAR leg pulls in SARB; everything else defaults to the US macro trio.
EVENT_RELEVANCE: dict[str, list[str]] = {
    name: (
        ["NFP", "US_CPI", "FOMC", "BOJ"] if "JPY" in name else
        ["NFP", "US_CPI", "FOMC", "SARB"] if "ZAR" in name else
        ["NFP", "US_CPI", "FOMC"]
    )
    for name in INSTRUMENTS
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def nfp_dates(start: dt.date, end: dt.date) -> list[pd.Timestamp]:
    """First Friday of each month between start and end."""
    out = []
    y, m = start.year, start.month
    while (y, m) <= (end.year, end.month):
        cal = calendar.monthcalendar(y, m)
        # first week that contains a Friday
        first_friday = cal[0][calendar.FRIDAY] or cal[1][calendar.FRIDAY]
        d = dt.date(y, m, first_friday)
        if start <= d <= end:
            out.append(pd.Timestamp(d))
        m += 1
        if m == 13:
            m, y = 1, y + 1
    return out


def build_event_calendar(start: dt.date, end: dt.date,
                         extra: pd.DataFrame | None) -> pd.DataFrame:
    """Long-format calendar: columns [date, event]."""
    rows = [{"date": d, "event": "NFP"} for d in nfp_dates(start, end)]
    for name, dates in [("FOMC", FOMC_DATES), ("BOJ", BOJ_DATES),
                        ("SARB", SARB_DATES), ("US_CPI", US_CPI_DATES)]:
        rows += [{"date": pd.Timestamp(d), "event": name} for d in dates]
    cal_df = pd.DataFrame(rows)
    if extra is not None and not extra.empty:
        extra = extra.copy()
        extra["date"] = pd.to_datetime(extra["date"])
        cal_df = pd.concat([cal_df, extra[["date", "event"]]], ignore_index=True)
    cal_df = cal_df.drop_duplicates()
    mask = (cal_df["date"].dt.date >= start) & (cal_df["date"].dt.date <= end)
    return cal_df.loc[mask].sort_values("date").reset_index(drop=True)


@st.cache_data(ttl=6 * 3600, show_spinner=False)
def fetch_daily(ticker: str, start: str, end: str) -> pd.DataFrame:
    df = yf.download(ticker, start=start, end=end,
                     interval="1d", auto_adjust=False, progress=False)
    if df.empty:
        return df
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    df = df[["Open", "High", "Low", "Close"]].dropna()
    df.index = pd.to_datetime(df.index).tz_localize(None)
    return df


def add_metrics(df: pd.DataFrame) -> pd.DataFrame:
    """Daily ATR% (true range / previous close) plus calendar features."""
    out = df.copy()
    prev_close = out["Close"].shift(1)
    tr = pd.concat([
        out["High"] - out["Low"],
        (out["High"] - prev_close).abs(),
        (out["Low"] - prev_close).abs(),
    ], axis=1).max(axis=1)
    out["atr_pct"] = 100.0 * tr / prev_close
    out["week_of_month"] = ((out.index.day - 1) // 7) + 1  # 1..5
    out["month"] = out.index.month
    return out.dropna(subset=["atr_pct"])


def days_to_nearest_event(index: pd.DatetimeIndex,
                          event_dates: pd.Series) -> np.ndarray:
    """Signed trading-agnostic calendar distance to the nearest event.
    Negative = event is ahead (approaching), positive = event has passed."""
    ev = np.sort(event_dates.values.astype("datetime64[D]"))
    days = index.values.astype("datetime64[D]")
    pos = np.searchsorted(ev, days)
    dist = np.full(len(days), np.inf)
    signed = np.zeros(len(days))
    for i, (d, p) in enumerate(zip(days, pos)):
        candidates = []
        if p < len(ev):
            candidates.append((ev[p] - d).astype(int))      # >= 0, upcoming
        if p > 0:
            candidates.append((ev[p - 1] - d).astype(int))  # <= 0, passed
        best = min(candidates, key=abs)
        # best = (event - today): positive when the event is upcoming.
        # Convention: event day = 0, days BEFORE are negative -> flip sign.
        signed[i] = -best
        dist[i] = abs(best)
    return signed


# ---------------------------------------------------------------------------
# Main render
# ---------------------------------------------------------------------------
def render_event_week_vol_tab() -> None:
    st.header("📅 Busy-Week Anatomy: week-of-month vs event-anchored volatility")
    st.caption(
        "Hypothesis: the 'busy week' in FX is the event calendar in disguise. "
        "If days-to-event shows a sharper volatility peak than week-of-month, "
        "trade the calendar, not the week number."
    )

    col1, col2, col3 = st.columns(3)
    with col1:
        years = st.slider("Lookback (years)", 1, 10, 4)
    with col2:
        window = st.slider("Event window (± days)", 3, 10, 5)
    with col3:
        chosen = st.multiselect("Instruments", sorted(INSTRUMENTS),
                                default=["USD/JPY", "USD/ZAR", "EUR/USD"])

    uploaded = st.file_uploader(
        "Optional: extend the event calendar (CSV with columns date,event)",
        type="csv")
    extra = pd.read_csv(uploaded) if uploaded else None

    if not chosen:
        st.info("Pick at least one instrument.")
        return

    end = dt.date.today()
    start = end - dt.timedelta(days=int(years * 365.25))
    cal_df = build_event_calendar(start, end, extra)

    naive_rows, event_rows, month_rows = [], [], []

    for name in chosen:
        raw = fetch_daily(INSTRUMENTS[name], str(start), str(end))
        if raw.empty:
            st.warning(f"No data for {name} — skipped.")
            continue
        df = add_metrics(raw)

        # 1) naive week-of-month
        wom = df.groupby("week_of_month")["atr_pct"].mean()
        for w, v in wom.items():
            naive_rows.append({"instrument": name, "week": int(w), "atr_pct": v})

        # 2) event-anchored, per relevant event type
        for ev_name in EVENT_RELEVANCE.get(name, ["NFP", "FOMC"]):
            ev_dates = cal_df.loc[cal_df["event"] == ev_name, "date"]
            if ev_dates.empty:
                continue
            d2e = days_to_nearest_event(df.index, ev_dates)
            sub = df.assign(d2e=d2e)
            sub = sub[sub["d2e"].abs() <= window]
            prof = sub.groupby("d2e")["atr_pct"].mean()
            for d, v in prof.items():
                event_rows.append({"instrument": name, "event": ev_name,
                                   "days_to_event": int(d), "atr_pct": v})

        # 3) seasonal sanity check: month-of-year
        mom = df.groupby("month")["atr_pct"].mean()
        for m, v in mom.items():
            month_rows.append({"instrument": name, "month": int(m), "atr_pct": v})

    if not naive_rows:
        st.error("No data fetched.")
        return

    naive = pd.DataFrame(naive_rows)
    events = pd.DataFrame(event_rows)
    months = pd.DataFrame(month_rows)

    # ---- Chart 1: week-of-month heatmap -----------------------------------
    st.subheader("1 · Naive view: mean daily ATR% by week of month")
    pivot = naive.pivot(index="instrument", columns="week", values="atr_pct")
    fig = px.imshow(pivot, text_auto=".2f", aspect="auto",
                    color_continuous_scale="RdYlGn_r",
                    labels=dict(color="ATR %"))
    st.plotly_chart(fig, use_container_width=True)

    # ---- Chart 2: event-anchored profiles ----------------------------------
    st.subheader("2 · Event-anchored view: ATR% vs days to event")
    st.caption("Day 0 = release/decision day. Negative = days before.")
    if not events.empty:
        for name in events["instrument"].unique():
            sub = events[events["instrument"] == name]
            fig2 = go.Figure()
            for ev_name, grp in sub.groupby("event"):
                grp = grp.sort_values("days_to_event")
                fig2.add_trace(go.Scatter(
                    x=grp["days_to_event"], y=grp["atr_pct"],
                    mode="lines+markers", name=ev_name))
            fig2.add_vline(x=0, line_dash="dash", line_color="gray")
            fig2.update_layout(title=name, height=320,
                               xaxis_title="days to event",
                               yaxis_title="mean ATR %",
                               margin=dict(t=40, b=30))
            st.plotly_chart(fig2, use_container_width=True)

    # ---- Chart 3: month-of-year seasonality --------------------------------
    st.subheader("3 · Seasonality check: ATR% by calendar month")
    pivot_m = months.pivot(index="instrument", columns="month", values="atr_pct")
    fig3 = px.imshow(pivot_m, text_auto=".2f", aspect="auto",
                     color_continuous_scale="RdYlGn_r",
                     labels=dict(color="ATR %"))
    st.plotly_chart(fig3, use_container_width=True)

    # ---- Verdict ------------------------------------------------------------
    st.subheader("4 · Verdict: which grouping explains more?")
    verdict_rows = []
    for name in naive["instrument"].unique():
        n = naive[naive["instrument"] == name]["atr_pct"]
        naive_spread = (n.max() - n.min()) / n.mean() * 100
        e = events[events["instrument"] == name]["atr_pct"] \
            if not events.empty else pd.Series(dtype=float)
        ev_spread = ((e.max() - e.min()) / e.mean() * 100) if len(e) else np.nan
        verdict_rows.append({
            "instrument": name,
            "week-of-month spread %": round(naive_spread, 1),
            "event-anchored spread %": round(ev_spread, 1),
            "calendar beats week#": bool(ev_spread > naive_spread)
            if not np.isnan(ev_spread) else None,
        })
    st.dataframe(pd.DataFrame(verdict_rows), use_container_width=True)
    st.caption(
        "Spread = (max − min) / mean of the grouped ATR% profile. A larger "
        "spread means that grouping separates quiet from busy days better."
    )

    # Log this research run to Postgres (audit trail, not trade_setups — this
    # is a seasonality/calendar-pattern study, not a directional pair+bias
    # signal). Deduped per instrument-set+settings via NotifyCache.
    _ewv_key = f"{','.join(sorted(chosen))}|{years}|{window}"
    if NotifyCache("event_week_vol_log").filter_new([_ewv_key]):
        log_tool_usage("event_week_vol", {
            "instruments": chosen, "years": years, "window": window,
            "verdict": verdict_rows,
        })


# ===========================================================================
# PAGE ENTRY — multipage (auto-run) + standalone (streamlit run)
# ===========================================================================

def _page() -> None:
    """Wire the tab into the Bloomberg-terminal multipage shell: shared theme,
    the uniform sidebar logo + navigation, then the tab body."""
    from src.ui.theme import BloombergTheme
    from src.pages_lib.navigation import render_sidebar_nav

    st.set_page_config(
        page_title="EWKV · Busy-Week Anatomy",
        page_icon="📅",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    BloombergTheme.apply()
    with st.sidebar:
        st.markdown("### 📅 Busy-Week Anatomy")
        st.caption("Week-of-month vs event-anchored volatility")
        st.divider()
        render_sidebar_nav()
    render_event_week_vol_tab()


# Streamlit executes a page module top-to-bottom on every run (the same way the
# other legacy pages self-initialise), so call the entry unconditionally.
_page()