"""The shared US/JP/ZA macro release calendar.

Lifted verbatim out of ``pages/event_week_vol_tab.py``, which owned it alone
until the Event Reaction Map needed the same dates. A calendar in a page
module cannot be imported — that page calls ``_page()`` unconditionally at
import time, so reading its dates would render the whole Busy-Week study — and
copying it would have produced two lists that drift. One list, two consumers.

Pure data and date arithmetic: no Streamlit, no network, no DB.

**The seeded lists go stale.** NFP is rule-computed and never runs out; FOMC,
BoJ, SARB, CPI and PPI are hand-maintained. :func:`next_release` returns
``None`` when a list is exhausted rather than extrapolating, because a
made-up release date presented as a default is worse than no default — it
would quietly stamp a signal with a release that never happened.
"""
from __future__ import annotations

import calendar
import datetime as dt
from datetime import date
from typing import Dict, List, Optional

import pandas as pd

from src.instruments import INSTRUMENTS as _REGISTRY_INSTRUMENTS

# The registry is the universe (src/instruments/registry.py), same as every
# other page — EVENT_RELEVANCE below is derived from it.
INSTRUMENTS: Dict[str, str] = {
    name: info.ticker for name, info in _REGISTRY_INSTRUMENTS.items()
}


# ---------------------------------------------------------------------------
# Event calendars.
# NFP is generated by rule (first Friday of the month).
# FOMC dates below are the *decision* days and are reliable through 2026.
# BoJ / SARB / CPI dates are best-effort seeds — VERIFY AND EXTEND these
# (or load your own via the CSV uploader in the UI; format: date,event).
# ---------------------------------------------------------------------------
FOMC_DATES = [
    # 2023
    "2023-02-01", "2023-03-22", "2023-05-03", "2023-06-14",
    "2023-07-26", "2023-09-20", "2023-11-01", "2023-12-13",
    # 2024
    "2024-01-31", "2024-03-20", "2024-05-01", "2024-06-12",
    "2024-07-31", "2024-09-18", "2024-11-07", "2024-12-18",
    # 2025
    "2025-01-29", "2025-03-19", "2025-05-07", "2025-06-18",
    "2025-07-30", "2025-09-17", "2025-10-29", "2025-12-10",
    # 2026 (scheduled)
    "2026-01-28", "2026-03-18", "2026-04-29", "2026-06-17",
    "2026-07-29", "2026-09-16", "2026-10-28", "2026-12-09",
]

# BoJ policy decision days (announcement = second day of meeting).
# Seed list — verify against boj.or.jp and extend.
BOJ_DATES = [
    "2024-01-23", "2024-03-19", "2024-04-26", "2024-06-14",
    "2024-07-31", "2024-09-20", "2024-10-31", "2024-12-19",
    "2025-01-24", "2025-03-19", "2025-05-01", "2025-06-17",
    "2025-07-31", "2025-09-19", "2025-10-30", "2025-12-19",
]

# SARB MPC decision Thursdays (6 per year: Jan/Mar/May/Jul/Sep/Nov).
# Seed list — verify against resbank.co.za and extend.
SARB_DATES = [
    "2024-01-25", "2024-03-27", "2024-05-30", "2024-07-18",
    "2024-09-19", "2024-11-21",
    "2025-01-30", "2025-03-20", "2025-05-29", "2025-07-31",
    "2025-09-18", "2025-11-20",
]

# US CPI release days — not rule-computable, seed with recent known dates
# and extend via CSV upload. (BLS publishes the schedule a year ahead.)
US_CPI_DATES = [
    "2024-01-11", "2024-02-13", "2024-03-12", "2024-04-10",
    "2024-05-15", "2024-06-12", "2024-07-11", "2024-08-14",
    "2024-09-11", "2024-10-10", "2024-11-13", "2024-12-11",
    "2025-01-15", "2025-02-12", "2025-03-12", "2025-04-10",
    "2025-05-13", "2025-06-11", "2025-07-15", "2025-08-12",
    "2025-09-11", "2025-10-15", "2025-11-13", "2025-12-10",
    "2026-01-13", "2026-02-11", "2026-03-11", "2026-04-10",
    "2026-05-12", "2026-06-10", "2026-07-14", "2026-08-12",
    "2026-09-11", "2026-10-13", "2026-11-10", "2026-12-10",
]

# US PPI release days. BLS publishes PPI within a day or two of CPI.
# Best-effort seeds on exactly the same footing as the CPI list above
# -- VERIFY against bls.gov/schedule/news_release/ and extend. A wrong
# seed costs a wrong *default* in a date picker, never a wrong result:
# the reaction map accepts any date you type and stores that one.
US_PPI_DATES = [
    "2025-01-14", "2025-02-13", "2025-03-13", "2025-04-11",
    "2025-05-15", "2025-06-12", "2025-07-16", "2025-08-14",
    "2025-09-10", "2025-10-16", "2025-11-14", "2025-12-11",
    "2026-01-14", "2026-02-12", "2026-03-12", "2026-04-14",
    "2026-05-13", "2026-06-11", "2026-07-15", "2026-08-13",
    "2026-09-15", "2026-10-14", "2026-11-12", "2026-12-11",
]

# Which event calendars matter for which instrument. Any JPY leg pulls in BOJ,
# any ZAR leg pulls in SARB; everything else defaults to the US macro trio.
EVENT_RELEVANCE: dict[str, list[str]] = {
    name: (
        ["NFP", "US_CPI", "US_PPI", "FOMC", "BOJ"] if "JPY" in name else
        ["NFP", "US_CPI", "US_PPI", "FOMC", "SARB"] if "ZAR" in name else
        ["NFP", "US_CPI", "US_PPI", "FOMC"]
    )
    for name in INSTRUMENTS
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def nfp_dates(start: dt.date, end: dt.date) -> list[pd.Timestamp]:
    """First Friday of each month between start and end."""
    out = []
    y, m = start.year, start.month
    while (y, m) <= (end.year, end.month):
        cal = calendar.monthcalendar(y, m)
        # first week that contains a Friday
        first_friday = cal[0][calendar.FRIDAY] or cal[1][calendar.FRIDAY]
        d = dt.date(y, m, first_friday)
        if start <= d <= end:
            out.append(pd.Timestamp(d))
        m += 1
        if m == 13:
            m, y = 1, y + 1
    return out


def build_event_calendar(start: dt.date, end: dt.date,
                         extra: pd.DataFrame | None) -> pd.DataFrame:
    """Long-format calendar: columns [date, event]."""
    rows = [{"date": d, "event": "NFP"} for d in nfp_dates(start, end)]
    for name, dates in [("FOMC", FOMC_DATES), ("BOJ", BOJ_DATES),
                        ("SARB", SARB_DATES), ("US_CPI", US_CPI_DATES),
                        ("US_PPI", US_PPI_DATES)]:
        rows += [{"date": pd.Timestamp(d), "event": name} for d in dates]
    cal_df = pd.DataFrame(rows)
    if extra is not None and not extra.empty:
        extra = extra.copy()
        extra["date"] = pd.to_datetime(extra["date"])
        cal_df = pd.concat([cal_df, extra[["date", "event"]]], ignore_index=True)
    cal_df = cal_df.drop_duplicates()
    mask = (cal_df["date"].dt.date >= start) & (cal_df["date"].dt.date <= end)
    return cal_df.loc[mask].sort_values("date").reset_index(drop=True)


# The seeded lists, by the name `build_event_calendar` and `EVENT_RELEVANCE`
# use. NFP is absent on purpose: it is rule-computed, not seeded.
_SEEDED: Dict[str, List[str]] = {
    "FOMC": FOMC_DATES,
    "BOJ": BOJ_DATES,
    "SARB": SARB_DATES,
    "US_CPI": US_CPI_DATES,
    "US_PPI": US_PPI_DATES,
}


def next_release(event: str, today: Optional[date] = None) -> Optional[date]:
    """The next occurrence of ``event`` on or after ``today``, or ``None``.

    NFP is generated by rule (first Friday of the month), so it never runs
    out. Everything else is a hand-maintained seed list, and a seed list
    *does* run out — when it has, this returns ``None`` rather than
    extrapolating a plausible-looking date. That distinction matters: the
    reaction map stamps every stored signal with the release date, so a
    fabricated default would attribute a read to a release that never
    happened, and the Source Scorecard would later resolve it against the
    wrong bars.

    The release day itself does not roll forward — on the morning of an FOMC,
    the next FOMC is today.
    """
    today = today or dt.date.today()

    if event == "NFP":
        first = _first_friday(today.year, today.month)
        if first >= today:
            return first
        year, month = ((today.year + 1, 1) if today.month == 12
                       else (today.year, today.month + 1))
        return _first_friday(year, month)

    upcoming = sorted(d for d in _SEEDED.get(event, ())
                      if date.fromisoformat(d) >= today)
    return date.fromisoformat(upcoming[0]) if upcoming else None


def _first_friday(year: int, month: int) -> date:
    """First Friday of the month, by the same rule `nfp_dates` applies."""
    cal = calendar.monthcalendar(year, month)
    day = cal[0][calendar.FRIDAY] or cal[1][calendar.FRIDAY]
    return date(year, month, day)
