FRED_API_KEY = "b95428dde387943cd19ecac1cf71d38f"
[email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "ckhotso@gmail.com"
#smtp_password = "xbafgclhawskmycx"
smtp_password = "pctqrrrnvwpixxwg"
sender = "ckhotso@gmail.com"
recipient = "mokhetkc@hotmail.com"
