FRED_API_KEY = "b95428dde387943cd19ecac1cf71d38f"
[email]
EMAIL_SMTP_HOST = "smtp.gmail.com"
EMAIL_SMTP_PORT = 587
EMAIL_SMTP_USER = "ckhotso@gmail.com"
EMAIL_SMTP_PASS = "pctqrrrnvwpixxwg"
sender = "ckhotso@gmail.com"
EMAIL_RECIPIENT = "mokhetkc@hotmail.com"